# Integration test harness useful for testing the GitHub Action itself
# Setup for this action is defined in action.yml
# This can be run locally using act (https://github.com/nektos/act) like this:
# act -v -j build --
# This will build the docker image that packages the GitHub Action and run it,
#     with verbose logging to show each step in detail

name: Process vocabularies
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Vocabulary action
        uses: isamplesorg/metadata_profile_earth_science@main
        # input variables 'action' and 'path' are defined in action.yml, and assigned values here
        # GitHub creates an environment variable for the input with the name INPUT_<VARIABLE_NAME>
        with:
          action: docs
          path: ${{ github.workspace }}
          # provide ttl file names without extensions; the base file name will be 
          #    used for output files with the appropriate extension.
          inputttl: earthenv_material_extension_mineral_group|earthenv_material_extension_rock_sediment|earthenv_sampled_feature_role|earthenv_specimen_type
          # these are the URIs for the ConceptScheme; there must be a conceptScheme defined in each vocabulary.
          inputvocaburi: ming:mineralgroupvocabulary|rksd:rocksedimentvocabulary|essfrole:sfrolevocabulary|esmat:essampletype
      - name: write message
        run: echo "github workspace " ${{ github.workspace }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: docs  #push the contents of the deployment folder into a
                                 # specific directory on the deployment branch
          commit-message: "new build of vocab docs"
